### ISSUE TITLE
Incorrect validation errors

### ISSUE THREAD

**Issue by vadeg** [asyncapi/editor#1]
Creating schema in editor causes an error `Cannot read property 'baseTopic' of undefined`.

##### Schema example
```
asyncapi: "1.2.0"
info:
  title: AsyncAPI Sample
  version: "1.0.0"
  description: |
    This is a simple example of an _AsyncAPI_ document.
  termsOfService: https://api.company.com/terms

servers:
  - url: api.company.com:{port}/{app-id}
    description: Allows you to connect using the MQTT protocol.
    scheme: mqtt
    variables:
      app-id:
        default: demo
        description: You can find your `app-id` in our control panel, under the auth tab.
      port:
        enum:
          - '5676'
          - '5677'
        default: '5676'
        
stream:
  framing:
    type: 'chunked'
    delimeter: '\r\n'
  read:
    - $ref: '#/components/messages/userSignedUp'
  write:
    - $ref: '#/components/messages/userSignedUp'
      
components:
  messages:
    userSignedUp:
      payload:
        type: object
        properties:
          key1:
            type: string
          key2:
            type: integer
```
The problem is with validation messages. If there is an error somewhere in schema (incorrect reference, wrong data type and etc.) editor always shows a message `Cannot read property 'baseTopic` what is not true.
The real problem here is the typo in `delimeter` property.

**Comment by vadeg** [comment]
I have tested Async API `generator` and it has the same behaviour. For example this is an error from generator
```
Invalid JSON obtained from the content of the AsyncAPI specification file
[ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
    params: [ [Array] ],
    message: 'Additional properties not allowed: payload,summary',
    path: '#/stream/read/0/payload',
    schemaId: 'http://asyncapi.hitchhq.com/v1/schema.json#',
    description: 'A deterministic version of a JSON Schema object.',
    [Symbol(z-schema/schema)]:
     { additionalProperties: false,
       properties: [Object],
       patternProperties: [Object],
       description: 'A deterministic version of a JSON Schema object.',
       type: 'object',
       '__$validated': true },
    [Symbol(z-schema/json)]:
     { asyncapi: '1.2.0',
       info: [Object],
       servers: [Array],
       stream: [Object],
       components: [Object] } } ]
Something went wrong:
TypeError: Cannot read property 'baseTopic' of undefined
```

The real error is not `Cannot read property 'baseTopic' of undefined` but `'Additional properties not allowed: payload,summary`.

**Comment by fmvilas** [comment]
You're right. Error messages are not very helpful in this case. The reason you also see it on the generator package is because the editor uses the generator package.

I'm sure this is not very complicated to fix but I don't have so much time for coding lately. Would you mind having a look at it yourself? I'd be very grateful.

**Comment by vadeg** [comment]
Ok. I will have a look.

**Comment by leozilla** [comment]
I always get one of those 2 validation errors even with very simple examples which contain `events`:
- `Cannot read property 'baseTopic' of undefined`
- `Cannot convert undefined or null to object`

The following example gives: `Cannot convert undefined or null to object`
```
asyncapi: '1.2.0'
info:
  title: Betr Public API.
  description: Betr public API for clients.
  version: '0.1.0'

servers:
  - url: myapp.api:8080/v1
    description: Local development server.
    scheme: ws

events:
  send:
    - $ref: '#/components/messages/ping'

components:
  messages:
    ping:
      summary: Ping me.
      payload:
        type: object
        properties:
          any:
            type: string
```

The simplest example which validates for me is:
```
asyncapi: '1.2.0'
info:
  title: Betr Public API.
  description: Betr public API for clients.
  version: '0.1.0'

servers:
  - url: myapp.api:8080/v1
    description: Local development server.
    scheme: ws

topics:
  accounts.1.0.event.user.signup:
    subscribe:
      $ref: "#/components/messages/userSignedUp"
    
components:
  messages:
    userSignedUp:
      payload:
        type: object
        properties:
          test:
            type: string
```

But if I add `events` to it like this:
```
asyncapi: '1.2.0'
info:
  title: Betr Public API.
  description: Betr public API for clients.
  version: '0.1.0'

servers:
  - url: myapp.api:8080/v1
    description: Local development server.
    scheme: ws

topics:
  accounts.1.0.event.user.signup:
    subscribe:
      $ref: "#/components/messages/userSignedUp"

events:
  send:
    - $ref: '#/components/messages/ping'
  receive:
    - $ref: '#/components/messages/ping'
    
components:
  messages:
    ping:
      summary: Ping me.
      payload:
        type: object
        properties:
          test:
            type: string
    userSignedUp:
      payload:
        type: object
        properties:
          test:
            type: string
```
I again get the error `Cannot read property 'baseTopic' of undefined`

For me it seems like this editor does not support `events` at all.

**Comment by fmvilas** [comment]
Yeah, `Cannot convert undefined or null to object` is definitely because the editor doesn't support other than `topics`, that's why it doesn't fail again on the second example.

For the other error, this is weird. I'll try to solve it as soon as possible. In the meantime, if you want to lend a hand, we'll be very grateful. We're just 3 people maintaining the whole thing (spec + tooling) and would love some help from the community 😊

**Comment by fmvilas** [comment]
### Action items
* Fix the generator package to try/catch awaits here: https://github.com/asyncapi/generator/blob/develop/lib/parser.js#L106. Also JSON.stringify and JSON.parse can fail and should be try/catch'ed.
* Add support on HTML template for events and stream sections: https://github.com/asyncapi/generator/tree/develop/templates/html.
* Make sure it fails nicely.
* Upgrade generator on this project.

**Comment by leozilla** [comment]
Thanks for your fast reply. I may try to fix one of your action items but unfortunatly I am not a javascript developer (and I think this stuff is written in JS if I am not mistaken) so I am not sure if I can/will do it.
Currently I am using the doc generator to generate html directly and this works quite well.

**Comment by fmvilas** [comment]
I understand. We appreciate any effort. If you need help or guidance just let me know.

**Comment by fmvilas** [comment]
I just realized this repo is using an outdated version of asyncapi-generator package. We should upgrade it to 0.6.0.

**Comment by fmvilas** [comment]
@leozilla @vadeg can you confirm this is already fixed? We just deployed @rmelian's PR #4.

**Comment by leozilla** [comment]
I can confirm that the editor is now able to parse and correctly display my api spec. Thanks!

**Comment by fmvilas** [comment]
Awesome! I'm glad it helped.
